//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerConfiguratorService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Builds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Builds()
        {
            this.BuildCaseCooling = new HashSet<BuildCaseCooling>();
            this.BuildHeadphones = new HashSet<BuildHeadphones>();
            this.BuildKeyboards = new HashSet<BuildKeyboards>();
            this.BuildMicrophones = new HashSet<BuildMicrophones>();
            this.BuildMonitors = new HashSet<BuildMonitors>();
            this.BuildMouses = new HashSet<BuildMouses>();
            this.BuildRAMs = new HashSet<BuildRAMs>();
            this.BuildServices = new HashSet<BuildServices>();
            this.BuildStorages = new HashSet<BuildStorages>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int BuildID { get; set; }
        public string BuildName { get; set; }
        public int GPUID { get; set; }
        public int CPUID { get; set; }
        public int MotherboardID { get; set; }
        public int CPUCoolingID { get; set; }
        public int PowerSupplyID { get; set; }
        public int CaseID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildCaseCooling> BuildCaseCooling { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildHeadphones> BuildHeadphones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildKeyboards> BuildKeyboards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildMicrophones> BuildMicrophones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildMonitors> BuildMonitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildMouses> BuildMouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildRAMs> BuildRAMs { get; set; }
        public virtual Cases Cases { get; set; }
        public virtual CPUCooling CPUCooling { get; set; }
        public virtual CPUs CPUs { get; set; }
        public virtual GPUs GPUs { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual PowerSupplies PowerSupplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildServices> BuildServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildStorages> BuildStorages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
