CREATE DATABASE [PCConfiguratorService]
GO
USE [PCConfiguratorService]
GO
/****** Object:  Table [dbo].[BuildCaseCooling]    Script Date: 05.06.2025 17:15:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BuildCaseCooling](
	[BuildCaseCoolingID] [int] IDENTITY(1,1) NOT NULL,
	[BuildID] [int] NOT NULL,
	[CaseCoolingID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_BuildCaseCooling] PRIMARY KEY CLUSTERED 
(
	[BuildCaseCoolingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BuildRAMs]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BuildRAMs](
	[BuildRAMID] [int] IDENTITY(1,1) NOT NULL,
	[BuildID] [int] NOT NULL,
	[RAMID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BuildRAMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Builds]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Builds](
	[BuildID] [int] IDENTITY(1,1) NOT NULL,
	[BuildName] [nvarchar](100) NOT NULL,
	[GPUID] [int] NOT NULL,
	[CPUID] [int] NOT NULL,
	[MotherboardID] [int] NOT NULL,
	[CPUCoolingID] [int] NOT NULL,
	[PowerSupplyID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,
 CONSTRAINT [PK__Builds__C5105161EFBEC862] PRIMARY KEY CLUSTERED 
(
	[BuildID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BuildStorages]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BuildStorages](
	[BuildStorageID] [int] IDENTITY(1,1) NOT NULL,
	[BuildID] [int] NOT NULL,
	[StorageID] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_BuildStorages] PRIMARY KEY CLUSTERED 
(
	[BuildStorageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CaseCooling]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CaseCooling](
	[CaseCoolingID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[FanSize] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK__CaseCool__2E5BBE57207D1490] PRIMARY KEY CLUSTERED 
(
	[CaseCoolingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CaseFormFactors]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CaseFormFactors](
	[CaseFFID] [int] IDENTITY(1,1) NOT NULL,
	[CaseFFName] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__CaseForm__EA3125839A457D28] PRIMARY KEY CLUSTERED 
(
	[CaseFFID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__CaseForm__85B69536E55F1551] UNIQUE NONCLUSTERED 
(
	[CaseFFName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cases]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cases](
	[CaseID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[CaseFFID] [int] NOT NULL,
	[MaxGPULength] [int] NOT NULL,
	[MaxCoolers] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
 CONSTRAINT [PK__Cases__6CAE526C5F7C75BD] PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CoolingTypes]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CoolingTypes](
	[CoolingTypeID] [int] IDENTITY(1,1) NOT NULL,
	[CoolingType] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__CoolingT__E3BE47A679AC9310] PRIMARY KEY CLUSTERED 
(
	[CoolingTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__CoolingT__593FA2FE2CF4CB5E] UNIQUE NONCLUSTERED 
(
	[CoolingType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPUCooling]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPUCooling](
	[CPUCoolingID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[CoolingTypeID] [int] NOT NULL,
	[MaxSupportedTDP] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
 CONSTRAINT [PK__CPUCooli__2D1CACE965B62189] PRIMARY KEY CLUSTERED 
(
	[CPUCoolingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CPUs]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CPUs](
	[CPUID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[SocketID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[Cores] [int] NOT NULL,
	[Threads] [int] NOT NULL,
	[BaseClock] [decimal](4, 2) NOT NULL,
	[BoostClock] [decimal](4, 2) NOT NULL,
	[TDP] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](max) NULL,
 CONSTRAINT [PK__CPUs__7D9B6772DBE20AC4] PRIMARY KEY CLUSTERED 
(
	[CPUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EfficiencyRatings]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EfficiencyRatings](
	[EfficiencyRatingID] [int] IDENTITY(1,1) NOT NULL,
	[Rating] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__Efficien__D664903D4EAC6C3A] PRIMARY KEY CLUSTERED 
(
	[EfficiencyRatingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Efficien__45BE90D51B34FDFB] UNIQUE NONCLUSTERED 
(
	[Rating] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GPUMemoryTypes]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GPUMemoryTypes](
	[GPUMemoryTypeID] [int] IDENTITY(1,1) NOT NULL,
	[MemoryType] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__GPUMemor__642DF4AFD98831F2] PRIMARY KEY CLUSTERED 
(
	[GPUMemoryTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__GPUMemor__73A51F4821F1D045] UNIQUE NONCLUSTERED 
(
	[MemoryType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GPUs]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GPUs](
	[GPUID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[VendorID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[GPUMemoryTypeID] [int] NOT NULL,
	[MemoryGB] [int] NOT NULL,
	[CoreBaseClock] [int] NOT NULL,
	[CoreBoostClock] [int] NULL,
	[MemoryClock] [int] NULL,
	[GPULength] [int] NOT NULL,
	[PowerConsumption] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](max) NULL,
 CONSTRAINT [PK__GPUs__8A41A909736C5F3D] PRIMARY KEY CLUSTERED 
(
	[GPUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Manufacturers]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Manufacturers](
	[ManufacturerID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Manufact__357E5CA1847EF643] PRIMARY KEY CLUSTERED 
(
	[ManufacturerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Manufact__3B9CDE2E80195F98] UNIQUE NONCLUSTERED 
(
	[ManufacturerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MotherboardFormFactor]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MotherboardFormFactor](
	[MotherboardFFID] [int] IDENTITY(1,1) NOT NULL,
	[MotheboardFFName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Motherbo__CE741AD6A84BFB7B] PRIMARY KEY CLUSTERED 
(
	[MotherboardFFID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Motherboards]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Motherboards](
	[MotherboardID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[SocketID] [int] NOT NULL,
	[RAMTypeID] [int] NOT NULL,
	[MotherboardFFID] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
 CONSTRAINT [PK__Motherbo__08FE22E683F19DEB] PRIMARY KEY CLUSTERED 
(
	[MotherboardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PowerSupplies]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PowerSupplies](
	[PowerSupplyID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[Wattage] [int] NOT NULL,
	[EfficiencyRatingID] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[PowerSupplyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RAMs]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RAMs](
	[RAMID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[CapacityGB] [int] NOT NULL,
	[SpeedMHz] [int] NOT NULL,
	[RAMTypeID] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[RAMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RAMTypes]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RAMTypes](
	[RAMTypeID] [int] IDENTITY(1,1) NOT NULL,
	[RAMType] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__RAMTypes__65AB1BB50E2B0DD7] PRIMARY KEY CLUSTERED 
(
	[RAMTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__RAMTypes__50BCA85FA664586B] UNIQUE NONCLUSTERED 
(
	[RAMType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sockets]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sockets](
	[SocketID] [int] IDENTITY(1,1) NOT NULL,
	[SocketName] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__Sockets__A1A1723F8792F452] PRIMARY KEY CLUSTERED 
(
	[SocketID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Sockets__96A6109612FB2CE7] UNIQUE NONCLUSTERED 
(
	[SocketName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Storages]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Storages](
	[StorageID] [int] IDENTITY(1,1) NOT NULL,
	[ManufacturerID] [int] NOT NULL,
	[Model] [nvarchar](50) NOT NULL,
	[StorageTypeID] [int] NOT NULL,
	[CapacityGB] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[ImagePath] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[StorageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StorageTypes]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StorageTypes](
	[StorageTypeID] [int] IDENTITY(1,1) NOT NULL,
	[StorageType] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK__StorageT__C94B8F7D0BC051B5] PRIMARY KEY CLUSTERED 
(
	[StorageTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__StorageT__16B9C42799F8B8D3] UNIQUE NONCLUSTERED 
(
	[StorageType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[RoleID] [int] NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[Patronymic] [nvarchar](50) NULL,
	[UserLogin] [nvarchar](50) NOT NULL,
	[UserPassword] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[UserLogin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vendors]    Script Date: 05.06.2025 17:15:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vendors](
	[VendorID] [int] IDENTITY(1,1) NOT NULL,
	[VendorName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Vendors__FC8618D36B7DE9BD] PRIMARY KEY CLUSTERED 
(
	[VendorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Vendors__7320A3571953D835] UNIQUE NONCLUSTERED 
(
	[VendorName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cases] ADD  CONSTRAINT [DF__Cases__MaxCooler__5AEE82B9]  DEFAULT ((1)) FOR [MaxCoolers]
GO
ALTER TABLE [dbo].[BuildCaseCooling]  WITH CHECK ADD  CONSTRAINT [FK_BuildCaseCooling_Builds] FOREIGN KEY([BuildID])
REFERENCES [dbo].[Builds] ([BuildID])
GO
ALTER TABLE [dbo].[BuildCaseCooling] CHECK CONSTRAINT [FK_BuildCaseCooling_Builds]
GO
ALTER TABLE [dbo].[BuildCaseCooling]  WITH CHECK ADD  CONSTRAINT [FK_BuildCaseCooling_CaseCooling] FOREIGN KEY([CaseCoolingID])
REFERENCES [dbo].[CaseCooling] ([CaseCoolingID])
GO
ALTER TABLE [dbo].[BuildCaseCooling] CHECK CONSTRAINT [FK_BuildCaseCooling_CaseCooling]
GO
ALTER TABLE [dbo].[BuildRAMs]  WITH CHECK ADD FOREIGN KEY([BuildID])
REFERENCES [dbo].[Builds] ([BuildID])
GO
ALTER TABLE [dbo].[BuildRAMs]  WITH CHECK ADD FOREIGN KEY([RAMID])
REFERENCES [dbo].[RAMs] ([RAMID])
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_Cases] FOREIGN KEY([CaseID])
REFERENCES [dbo].[Cases] ([CaseID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_Cases]
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_CPUCooling] FOREIGN KEY([CPUCoolingID])
REFERENCES [dbo].[CPUCooling] ([CPUCoolingID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_CPUCooling]
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_CPUs] FOREIGN KEY([CPUID])
REFERENCES [dbo].[CPUs] ([CPUID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_CPUs]
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_GPUs] FOREIGN KEY([GPUID])
REFERENCES [dbo].[GPUs] ([GPUID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_GPUs]
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_Motherboards] FOREIGN KEY([MotherboardID])
REFERENCES [dbo].[Motherboards] ([MotherboardID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_Motherboards]
GO
ALTER TABLE [dbo].[Builds]  WITH CHECK ADD  CONSTRAINT [FK_Builds_PowerSupplies] FOREIGN KEY([PowerSupplyID])
REFERENCES [dbo].[PowerSupplies] ([PowerSupplyID])
GO
ALTER TABLE [dbo].[Builds] CHECK CONSTRAINT [FK_Builds_PowerSupplies]
GO
ALTER TABLE [dbo].[BuildStorages]  WITH CHECK ADD  CONSTRAINT [FK_BuildStorages_Builds] FOREIGN KEY([BuildID])
REFERENCES [dbo].[Builds] ([BuildID])
GO
ALTER TABLE [dbo].[BuildStorages] CHECK CONSTRAINT [FK_BuildStorages_Builds]
GO
ALTER TABLE [dbo].[BuildStorages]  WITH CHECK ADD  CONSTRAINT [FK_BuildStorages_Storages] FOREIGN KEY([StorageID])
REFERENCES [dbo].[Storages] ([StorageID])
GO
ALTER TABLE [dbo].[BuildStorages] CHECK CONSTRAINT [FK_BuildStorages_Storages]
GO
ALTER TABLE [dbo].[CaseCooling]  WITH CHECK ADD  CONSTRAINT [FK_CaseCooling_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[CaseCooling] CHECK CONSTRAINT [FK_CaseCooling_Manufacturers]
GO
ALTER TABLE [dbo].[Cases]  WITH CHECK ADD  CONSTRAINT [FK_Cases_CaseFormFactors] FOREIGN KEY([CaseFFID])
REFERENCES [dbo].[CaseFormFactors] ([CaseFFID])
GO
ALTER TABLE [dbo].[Cases] CHECK CONSTRAINT [FK_Cases_CaseFormFactors]
GO
ALTER TABLE [dbo].[Cases]  WITH CHECK ADD  CONSTRAINT [FK_Cases_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[Cases] CHECK CONSTRAINT [FK_Cases_Manufacturers]
GO
ALTER TABLE [dbo].[CPUCooling]  WITH CHECK ADD  CONSTRAINT [FK_CPUCooling_CoolingTypes] FOREIGN KEY([CoolingTypeID])
REFERENCES [dbo].[CoolingTypes] ([CoolingTypeID])
GO
ALTER TABLE [dbo].[CPUCooling] CHECK CONSTRAINT [FK_CPUCooling_CoolingTypes]
GO
ALTER TABLE [dbo].[CPUCooling]  WITH CHECK ADD  CONSTRAINT [FK_CPUCooling_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[CPUCooling] CHECK CONSTRAINT [FK_CPUCooling_Manufacturers]
GO
ALTER TABLE [dbo].[CPUs]  WITH CHECK ADD  CONSTRAINT [FK_CPUs_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[CPUs] CHECK CONSTRAINT [FK_CPUs_Manufacturers]
GO
ALTER TABLE [dbo].[CPUs]  WITH CHECK ADD  CONSTRAINT [FK_CPUs_Sockets] FOREIGN KEY([SocketID])
REFERENCES [dbo].[Sockets] ([SocketID])
GO
ALTER TABLE [dbo].[CPUs] CHECK CONSTRAINT [FK_CPUs_Sockets]
GO
ALTER TABLE [dbo].[GPUs]  WITH CHECK ADD  CONSTRAINT [FK_GPUs_GPUMemoryTypes] FOREIGN KEY([GPUMemoryTypeID])
REFERENCES [dbo].[GPUMemoryTypes] ([GPUMemoryTypeID])
GO
ALTER TABLE [dbo].[GPUs] CHECK CONSTRAINT [FK_GPUs_GPUMemoryTypes]
GO
ALTER TABLE [dbo].[GPUs]  WITH CHECK ADD  CONSTRAINT [FK_GPUs_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[GPUs] CHECK CONSTRAINT [FK_GPUs_Manufacturers]
GO
ALTER TABLE [dbo].[GPUs]  WITH CHECK ADD  CONSTRAINT [FK_GPUs_Vendors] FOREIGN KEY([VendorID])
REFERENCES [dbo].[Vendors] ([VendorID])
GO
ALTER TABLE [dbo].[GPUs] CHECK CONSTRAINT [FK_GPUs_Vendors]
GO
ALTER TABLE [dbo].[Motherboards]  WITH CHECK ADD  CONSTRAINT [FK_Motherboards_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[Motherboards] CHECK CONSTRAINT [FK_Motherboards_Manufacturers]
GO
ALTER TABLE [dbo].[Motherboards]  WITH CHECK ADD  CONSTRAINT [FK_Motherboards_MotherboardFormFactor] FOREIGN KEY([MotherboardFFID])
REFERENCES [dbo].[MotherboardFormFactor] ([MotherboardFFID])
GO
ALTER TABLE [dbo].[Motherboards] CHECK CONSTRAINT [FK_Motherboards_MotherboardFormFactor]
GO
ALTER TABLE [dbo].[Motherboards]  WITH CHECK ADD  CONSTRAINT [FK_Motherboards_RAMTypes] FOREIGN KEY([RAMTypeID])
REFERENCES [dbo].[RAMTypes] ([RAMTypeID])
GO
ALTER TABLE [dbo].[Motherboards] CHECK CONSTRAINT [FK_Motherboards_RAMTypes]
GO
ALTER TABLE [dbo].[Motherboards]  WITH CHECK ADD  CONSTRAINT [FK_Motherboards_Sockets] FOREIGN KEY([SocketID])
REFERENCES [dbo].[Sockets] ([SocketID])
GO
ALTER TABLE [dbo].[Motherboards] CHECK CONSTRAINT [FK_Motherboards_Sockets]
GO
ALTER TABLE [dbo].[PowerSupplies]  WITH CHECK ADD  CONSTRAINT [FK_PowerSupplies_EfficiencyRatings] FOREIGN KEY([EfficiencyRatingID])
REFERENCES [dbo].[EfficiencyRatings] ([EfficiencyRatingID])
GO
ALTER TABLE [dbo].[PowerSupplies] CHECK CONSTRAINT [FK_PowerSupplies_EfficiencyRatings]
GO
ALTER TABLE [dbo].[PowerSupplies]  WITH CHECK ADD  CONSTRAINT [FK_PowerSupplies_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[PowerSupplies] CHECK CONSTRAINT [FK_PowerSupplies_Manufacturers]
GO
ALTER TABLE [dbo].[RAMs]  WITH CHECK ADD  CONSTRAINT [FK_RAMs_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[RAMs] CHECK CONSTRAINT [FK_RAMs_Manufacturers]
GO
ALTER TABLE [dbo].[RAMs]  WITH CHECK ADD  CONSTRAINT [FK_RAMs_RAMTypes] FOREIGN KEY([RAMTypeID])
REFERENCES [dbo].[RAMTypes] ([RAMTypeID])
GO
ALTER TABLE [dbo].[RAMs] CHECK CONSTRAINT [FK_RAMs_RAMTypes]
GO
ALTER TABLE [dbo].[Storages]  WITH CHECK ADD  CONSTRAINT [FK_Storages_Manufacturers] FOREIGN KEY([ManufacturerID])
REFERENCES [dbo].[Manufacturers] ([ManufacturerID])
GO
ALTER TABLE [dbo].[Storages] CHECK CONSTRAINT [FK_Storages_Manufacturers]
GO
ALTER TABLE [dbo].[Storages]  WITH CHECK ADD  CONSTRAINT [FK_Storages_StorageTypes] FOREIGN KEY([StorageTypeID])
REFERENCES [dbo].[StorageTypes] ([StorageTypeID])
GO
ALTER TABLE [dbo].[Storages] CHECK CONSTRAINT [FK_Storages_StorageTypes]
GO
ALTER TABLE [dbo].[Users]  WITH CHECK ADD  CONSTRAINT [FK_Users_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
GO
ALTER TABLE [dbo].[Users] CHECK CONSTRAINT [FK_Users_Roles]
GO
